version: '3'

services:
  mage2kishbox-mgt-dev:
    build: "./mgt-dev/"
    container_name: "mgt-dev"
    depends_on:
      - mage2kishbox-mailhog
    volumes:
      - mysqldata:/var/lib/mysql
      - nginxdata:/etc/nginx/
      - cloudpanel:/home/cloudpanel

    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
      - "22:22"
      - "3306:3306"
      - "9200:9200"
      - "15672:15672"
    #networks:
      #docker-mage2kishbox-network:
        #ipv4_address: 145.23.1.1

  mage2kishbox-mailhog:
    platform: linux/amd64
    image: mailhog/mailhog
    container_name: "mailhog"
    user: root
    expose:
      - 80
    ports:
      - "1025:80"
    environment:
      MH_API_BIND_ADDR: 0.0.0.0:80
      MH_UI_BIND_ADDR: 0.0.0.0:80
    #networks:
      #docker-mage2kishbox-network:
        #ipv4_address: 145.23.1.4

#networks:
  #docker-mage2kishbox-network:
    #driver: bridge
    #ipam:
      #driver: default
      #config:
        #- subnet: 145.23.0.0/16

volumes:
  mysqldata:
  nginxdata:
  cloudpanel:
  
